public_html/core/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
]

public_html/pruebaformularios/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import PersonaList, add_persona


prueba_patterns = ([
    path('', add_persona, name='plist'),
    path('listar/', login_required(PersonaList.as_view()), name='padd'),
    ], "inscripcion")

public_html/webplayground/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from pages.urls import pages_patterns
from pruebaformularios.urls import prueba_patterns


urlpatterns = [
    path('', include('core.urls')),
    path('pages/', include(pages_patterns)),
    path('admin/', admin.site.urls),
    path('inscripcion/', include(prueba_patterns, namespace="upersonas")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Titulos personalizados admin
admin.site.site_header ="IAPP - Instituto de Actualización y Perfecionamiento Profesional"
admin.site.index_title = "Panel de edición"
admin.site.site_title = "IAPP"

public_html/pruebaformularios/models.py
from django.forms import ModelForm, TextInput, Textarea
from django.db import models
from django import forms


class Persona(models.Model):

    GENDER_CHOICES = (
        ('NO', 'NO'),
        ('SI', 'SI'),
    )
    nombre = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=60, verbose_name="Apellido")
    dni = models.CharField(help_text="Dni válido ej. 22222222", max_length=8)
    direccion = models.CharField(max_length=100, verbose_name="Localidad", help_text="Ej. Rosario 2000")
    telefono = models.CharField(max_length=18)
    email = models.EmailField()
    procurador = models.CharField(max_length=2, choices=GENDER_CHOICES)
    codigocurso = models.CharField(max_length=7, blank=True)
    nombrecurso = models.CharField(max_length=60, blank=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

    def __str__(self):
        return self.dni

    def save(self, force_insert=False, force_update=False):
        self.nombre = self.nombre.upper()
        self.apellidos = self.apellidos.upper()
        self.direccion = self.direccion.upper()
        super(Persona, self).save(force_insert, force_update)


class PersonaForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].label = ''
        self.fields['apellidos'].label = ''
        self.fields['dni'].label = ''
        self.fields['direccion'].label = ''
        self.fields['telefono'].label = ''
        self.fields['email'].label = ''
        self.initial['procurador'] = 'NO'

        #self.fields['house'].widget.attrs['size'] = '1'
        #self.fields['house'].style = 'font-size:13px;width:60px;'

    class Meta:

        model = Persona
        fields = ('nombre', 'apellidos', 'dni', 'direccion', 'telefono', 'email', 'procurador', 'codigocurso', 'nombrecurso')
        widgets = {
            'nombre': forms.TextInput(attrs={'placeholder': 'Nombre', 'onkeyup' : 'this.value = this.value.toUpperCase();'}),
            'apellidos': forms.TextInput(attrs={'placeholder': 'Apellido', 'onkeyup' : 'this.value = this.value.toUpperCase();'}),
            'direccion': forms.TextInput(attrs={'placeholder': 'Localidad', 'onkeyup' : 'this.value = this.value.toUpperCase();'}),
            'telefono': forms.TextInput(attrs={'placeholder': 'Telefono', 'onKeypress': 'if (event.keyCode < 45 || event.keyCode > 57) event.returnValue = false;'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'procurador': forms.Select(attrs={'style': 'font-size:13px;width:60px;'}),
            'dni': forms.TextInput(attrs={'minlength': '8', 'placeholder': 'Dni', 'onKeypress': 'if (event.keyCode < 45 || event.keyCode > 57) event.returnValue = false;'}),
        }

public_html/pruebaformularios/views.py
from django.views.generic import View, ListView
from django.shortcuts import render, redirect
#from django.core.mail import EmailMessage
from django.core.mail import send_mail
from .models import Persona
from .models import PersonaForm
from pages.models import Page
from .filters import SnippetFilter
from datetime import datetime
from django.utils import formats


class PersonaList(ListView):
    template_name = "pruebaformularios/personas_list.html"
    model = Persona

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['filter'] = SnippetFilter(self.request.GET, queryset=self.get_queryset())
        return context


def add_persona(request):
    
    form_class = PersonaForm
    form = form_class(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            datos = form.cleaned_data['email']
            nombre_f = form.cleaned_data['nombre']
            apellido_f = form.cleaned_data['apellidos']
            dni_f = form.cleaned_data['dni']
            nombreyapellido_f = nombre_f + " " + apellido_f
            nombrecurso_f = form.cleaned_data['nombrecurso']
            codigocurso_f = form.cleaned_data['codigocurso']
            nombre_f = nombre_f.upper()
            apellido_f = apellido_f.upper()
            date_joined = datetime.now()
            formatted_datetime = formats.date_format(date_joined, "d/m/Y H:m:s")
            
            per_existe = Persona.objects.filter(dni=dni_f, codigocurso=codigocurso_f).exists()
            if per_existe:
                return render(request, 'pruebaformularios/fail.html')
            else:
                #print('NO')
                html_message = """<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
                <html xmlns="http://www.w3.org/1999/xhtml">
                <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                </head>
                <body style="margin: 0; padding:0;">
                <table border="0"  cellpadding="0" cellspacing="0" width="100%">
                <tr bgcolor="white">
                <td>
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-bottom: 2px solid #eaeaea;">
                <tr>
                <td bgcolor="white" style="padding: 0px 0px 10px 0px">
                <center>
                <img src="https://iapprosario.com/media/TITMAIL3.png" alt="Smiley face" />
                </center>
                </td>
                </tr>
                </table>
                </td>
                </tr>
                <tr bgcolor="white">
                <td>
                <table bgcolor="#ffffff" align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;">
                <tr>
                <td style="padding: 20px">
                <table  bgcolor="#ffffff" style="border-bottom: 2px solid #eaeaea;" border="0" cellpadding="0" cellspacing="0" width="100%"><br>
                Gracias """ + nombreyapellido_f + """&nbsp; por preinscribirse.
			    Por favor imprima el comprobante y recorte por las lineas punteadas o por el simbolo igual,
                deberá entregar y abonar el comprobante de preinscripción en el colegio de procuradores, en la fecha prevista. <br>
    
                <b><u>Por favor tome nota de la siguiente información</u></b><br>

                <br>Recuerde acudir con DNI al momento de abonar el arancel.<br>
                Si es procurador debera acreditar la condición de tal al momento del pago.<br>
                Podrá abonar la inscripción en efectivo en el Colegio de Procuradores de 8.30 a 12.30<br>
                (Balcarce 1651, Planta Baja Tribunales Rosario).<br>

                <br>También puede abonar por transferencia o depósito bancario:<br>
                <b><u>Datos Bancarios:</u></b><br>
                CUIT: 30-68547215-1<br>
                Banco: Nuevo Banco de Santa Fe<br>
                Sucursal: AG Tribunales Rosario<br>
                Cuenta: 00803027166/06<br>
                Cbu: 3300008220080027166068<br>
                Una vez realizado el pago deberá enviar al correo electrónico colprocuradores@arnetbiz.com.ar<br>
                desde el email que ud registro en el formulario, los siguientes datos:<br>
                – Nombre y apellido<br>
                – Dni<br>
                – Foto del comprobante de preinscripcion.<br>
			    – Foto del comprobante de deposito o transferencia.<br>
                <tr>
                <td style="color: #53545e;font-weight: bold;font-family: Arial, Verdana, sans-serif;padding: 25px 0px 25px 0px;"><br>
                <img src="https://iapprosario.com/media/tijera.png" alt="Smiley face"  WIDTH=30 HEIGHT=30 />
                ------------------------------------------------------------------------------------<br>
                =================================================================<br>
                <br>Comprobante de preinscripción<br>
                _________________________________________________________________<br>
                <br><b>Nombre de la jornada/curso:</b> """+ nombrecurso_f +""" <br>
                <br><b>Código del curso: </b> """ + codigocurso_f + """ <br>
                _________________________________________________________________<br>
                <br><b>Nombre y Apellido:</b> """ + nombreyapellido_f + """ <br>
                <b>Dni:</b> """ + dni_f + """ <br>
                <b>Fecha / Hora de inscripción: </b>""" + formatted_datetime + """<br>
                <br>
                =================================================================<br>
                --------------------------------------------------------------------------------------<br>
                </td>
                </tr>
                </table>
                </td>
                </tr>                       
                </table>
                </td>
                </tr>   
                <tr>
                <td style="padding: 35px 0px 50px 0px">
                <center>
                Para mas  información visite nuestro sitio web<br>
                <a href="https://www.iapprosario.com" style="background-color: #53545e;padding: 5px 10px;color: #ffffff;text-decoration: none;font-family: Arial, Verdana, sans-serif;"><br>Visitar web</a> 
                </center>
                </td>
                </tr>    
                </table>
                </body>
                </html>"""
       
                email_body="Gracias por preinscribirse, recuerde abonar el arancel dentro de la fecha prevista."
                #email = EmailMessage('Gracias por inscribirse a la Jornada.', email_body,
                #'IAPP Rosario <noresponder@iapprosario.com>', to=[datos], faili)
                #email.content_subtype = "html"  # Main content is now text/html
                #email.send()
                send_mail(
                'Gracias por inscribirse a la Jornada.',
                email_body,
                'IAPP Rosario <noresponder@iapprosario.com>',
                [datos],
                fail_silently=False, html_message=html_message
                )
                new_persona = form.save()
                form = PersonaForm()
                return render(request, 'pruebaformularios/gracias.html')
    return render(request, 'pruebaformularios/persona_form.html', {'form': form})

public_html/pruebaformularios/templates/pruebaformularios/fail.html
<!DOCTYPE html>
<html>
<head>
        <link href="https://iapprosario.com/static/core/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://iapprosario.com/static/core/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="https://iapprosario.com/static/core/css/clean-blog.min.css" rel="stylesheet">
<title>Preinscripcion no exitosa!</title>

</head>
<body>
    <br>
    <center><STRONG><UNDERLINE><div style="text-shadow: 2px 1px 1px gray;color:#f0f0f0;">FORMULARIO DE INSCRIPCION</div></UNDERLINE></STRONG></center>
    <br>
<main role="main"  style="background-color:#333333;">
    <div class="container" style="width:50%;background-color:#ababab;box-shadow: 0 0 5px 5px grey;">


                <div class="col-xl-12 col-lg-12 col-md-12 mx-auto mt-2 mb-2">
                 <center>

                     <div  style="padding-top:15px;text-shadow: 2px 1px 1px gray;color:#f0f0f0;color:red;"><h4>La preinscripción ha fallado!!</h4><br>
                             Ud. ya esta preinscripto en este curso o jornada.

                      </div>


                 </center>
                            <center>
                            {% load user_agents %}
                            {% if request|is_mobile or request|is_tablet %}
                            <br><a style="font-size:small;" class="btn btn-primary btn-sm" href="{% url 'home' %}" ><strong>CERRAR</strong></a>
                            {% else %}
                            <br><a style="font-size:medium;" class="btn btn-primary btn-sm" href="{% url 'home' %}" ><strong>CERRAR</strong></a>
                            {% endif %}
                                <br>
                            </center>
         </div>
        <br>
    </div>
</main>
</body>
<footer>

            <p class="copyright" style="color:white">Copyright &copy; 2019 · Charlie Pioli</p>


    </footer>
</html>

public_html/pruebaformularios/templates/pruebaformularios/gracias.html
{% load static %}
{% block content %}
<head>
    <link href="https://iapprosario.com/static/core/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://iapprosario.com/static/core/css/clean-blog.min.css" rel="stylesheet">
    <link href="{% static 'core/css/clean-blog.min.css' %}" rel="stylesheet">
	<META HTTP-EQUIV="REFRESH" CONTENT="15;URL={% url 'home' %}">
<title>Preinscripcion Exitosa</title>

</head>
<br>
<center><STRONG><UNDERLINE><h3 style="text-shadow: 2px 1px 1px gray;color:#f0f0f0";>PREINSCRIPCION EXITOSA!</h3></UNDERLINE></STRONG></center>
<main role="main"  style="background-color:#333333;">
			{% load user_agents %}
			{% if request|is_mobile or request|is_tablet %}

				<div class="container" style="width:93%;background-color:#ababab;box-shadow: 0 0 10px 5px grey;">
			{% else %}
				<div class="container" style="width:65%;background-color:#ababab;box-shadow: 0 0 10px 5px grey;">
			{% endif %}
			<div class="col-xs-12 col-xl-10 col-lg-10 col-md-10 mt-8 mb-3 mx-auto">
			<div class="row">
			<justify>
			  <div  style="padding-top:15px;text-shadow: 2px 1px 1px gray;color:#f0f0f0;color:black;"><h5><br>Gracias por preinscribirse!!</h5> Recuerde abonar el arancel antes del tiempo del vencimiento respectivo, el mismo figura en la descripción del curso en la sección arancel.<br>
			      <br>
                         <h7>
                            En unos minutos le llegara un correo electronico a su casilla de email que ingreso
                            en el formulario, si no aparece en bandeja de entrada revise la carpeta "correo no deseado".
							<br> En segundos sera redirigido a la pagina principal.
                         </h7>
               </div>
			       <br>
		   </justify>
		  </div>
		  </div>
		</div>
</main>
{% endblock %}
<footer>

	<p class="copyright" style="color:white">Copyright &copy; 2019 · Charlie Pioli</p>


</footer>

public_html/pruebaformularios/templates/pruebaformularios/persona_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Inscripción{% endblock %}
{% block background %}{% load static %}{% static 'core/img/contact-bg.jpg' %}{% endblock %}
{% block headers %}
  <h3 STYLE="text-shadow: 3px 3px 2px #434242;color:#f0f0f0" >INSTITUTO DE ACTUALIZACIÓN Y PERFECCIONAMIENTO PROFESIONAL</h3>
  <h8  STYLE="text-shadow: 3px 3px 2px #434242;padding: 5px 0 0 0;" >Colegio de Procuradores de Rosario</h8>
{% endblock %}

<html>
{% block content %}
<head>

     <script>


       function tieneletras(){
           var letras="abcdefghyjklmnñopqrstuvwxyz";
           var dni = document.getElementById("id_dni");
           var texto = dni.value;
           texto = texto.toLowerCase();
           for(i=0; i<texto.length; i++){
              if (letras.indexOf(texto.charAt(i),0)!=-1){
                   alert("Asegurese de ingresar solo numeros");
                   dni.focus();
                   return false;
              }
           }
           return true;
        }

       function selco(){

            var url_string = window.location.href
            var url = new URL(url_string);
            var c = url.searchParams.get("cod");
            var txt = c
            var d = url.searchParams.get("ncu");
            var txn = d
            document.getElementById("custi").value = txt
            document.getElementById("nombrejornada").value = txn
            document.getElementById("id_nombre").value = ""
            var sel = document.getElementById('id_codcurso');
            var opt = document.createElement('option');
            opt.appendChild( document.createTextNode(txt) );
            opt.value = 'option value';
            sel.appendChild(opt);
            $('#id_nombre').focus();
       }

        function validaNumericos(){
                 var inputtxt = document.getElementById('id_dni');
                 var valor = inputtxt.value;
                 for(i=0;i<valor.length;i++){
                     var code=valor.charCodeAt(i);
                     if(code<=48 || code>=57){
                        inputtxt.value="";
                        return;
                     }
                 }
        }
     </script>

</head>

<body onload="selco()">

<left>
<br>
<center><STRONG><UNDERLINE><h3 style="text-shadow: 2px 1px 1px gray;color:#f0f0f0";>FORMULARIO DE INSCRIPCION</h3></UNDERLINE></STRONG></center>
<main role="main"  style="background-color:#333333;">
{% load user_agents %}
{% if request|is_mobile or request|is_tablet %}

    <div class="container" style="width:95%;background-color:#ababab;box-shadow: 0 0 10px 5px grey;">
{% else %}
        <div class="container" style="width:50%;background-color:#ababab;box-shadow: 0 0 10px 5px grey;">
{% endif %}
         <div class="row mt-2">
                <div class="col-xl-12 col-lg-12 col-md-12 mt-6">
                  <div class="bg-faded rounded p-3">
                     <form class="" action="{% url 'upersonas:plist' %}" method="post" id="formulario" onsubmit="return tieneletras()">
                            {% csrf_token %}
                        <div class="form-row">
                          <div class="form-group col-md-12 mt-2">
                              <div align="left" style="padding-bottom: 10px;"><h8>Código curso:</h8> <select style="font-size:14px;width:110px;" id="id_codcurso"name="codcurso"></select></div>
                            {{ form.nombre|as_crispy_field  }}
                            {{ form.apellidos|as_crispy_field }}
                            {{ form.dni|as_crispy_field }}
                            {{ form.direccion|as_crispy_field }}
                            {{ form.telefono|as_crispy_field }}
                            {{ form.email|as_crispy_field }}
                             <div align="left" style="padding-bottom: 10px;">Procurador: {{ form.procurador }}</div>
                                 {% load user_agents %}
                                 {% if request|is_mobile or request|is_tablet %}
                                    <input style="width:100%;" class="btn btn-primary btn-sm btn-block" type="submit" value="Inscribirse" />
                                     <br><a style="font-size:small;" class="btn btn-primary btn-sm" href="{% url 'pages:pages' %}" ><strong>CERRAR</strong></a>
                                 {% else %}
                                <input style="font-size:large;width:100%;" class="btn btn-primary btn-md btn-block" type="submit" value="Inscribirse" />
                                <center> <br><a style="font-size:medium;" class="btn btn-primary btn-sm" href="{% url 'pages:pages' %}" ><strong>CERRAR</strong></a></center>
                                 {% endif %}
                          </div>
                        </div>
                         <input type="hidden" id="nombrejornada" name="nombrecurso"/>
                      <input type="hidden" id="custi" name="codigocurso"/>
                     </form>
                  </div>
                </div>
         </div>
    </div>
</main>
</left>

</body>
{% endblock %}
</html>

public_html/pruebaformularios/templates/pruebaformularios/personas_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Reporte Suscriptores{% endblock %}
{% block background %}{% load static %}{% static 'core/img/contact-bg.jpg' %}{% endblock %}
 {% block headers %}
  <h3 STYLE="text-shadow: 3px 3px 2px #434242;color:#f0f0f0" >INSTITUTO DE ACTUALIZACIÓN Y PERFECCIONAMIENTO PROFESIONAL</h3>
  <h8  STYLE="text-shadow: 3px 3px 2px #434242;padding: 5px 0 0 0;" >Colegio de Procuradores de Rosario</h8>

{% endblock %}
{% block content %}
<head>
<script>
	function fnExcelReport()
	{
		var sTable = "<center><h3>IAPP ROSARIO</h3></center>"
		var sTable = sTable + "<center><h4>LISTA SUSCRIPTORES</h4></center>"
        var sTable = sTable + document.getElementById('tab').innerHTML;

        var style = "<style>";
        style = style + "table {width: 100%;font: 18px Calibri;}";
        style = style + "table, th, td {border: solid 1px #DDD; bgcolor:#87AFC6; border-collapse: collapse;";
        style = style + "padding: 2px 3px;text-align: center;}";
        style = style + "</style>";

        // CREATE A WINDOW OBJECT.
        var win = window.open('', '', 'height=700,width=700');

        win.document.write('<html><head>');

        win.document.write(style);          // ADD STYLE INSIDE THE HEAD TAG.
        win.document.write('</head>');
        win.document.write('<body>');
        win.document.write(sTable);         // THE TABLE CONTENTS INSIDE THE BODY TAG.
        win.document.write('</body></html>');

        win.document.close(); 	// CLOSE THE CURRENT WINDOW.

        win.print();    // PRINT THE CONTENTS.

	}
	</script>
</head>
<body>
<br>
<center><STRONG><UNDERLINE><h3 style="text-shadow: 2px 1px 1px gray;color:#f0f0f0";>REPORTE SUSCRIPTORES</h3></UNDERLINE></STRONG></center>
<main role="main"  style="background-color:#333333;">
    <div class="container mb-4" style="background-color:#c8c8c8;box-shadow: 0 0 10px 5px grey;">

		<div class="row mt-4">

	<div class="col-md-4 mt-4 mx-4">
		<form method="GET" action="">

			{{ filter.form|crispy }}

			<button type="submit" class="btn btn-m btn-primary">Filtrar</button>&nbsp;&nbsp;<button  class="btn btn-m btn-primary"  onclick="javascript:fnExcelReport()">Imprimir/Exportar PDF</button>
		</form>
	</div>
		</div>

 <div class="row">

<div class="col-md-12 mx-auto">
            <br>




<br>
    <div id="customers" class="table-responsive">
		<iframe id="txtArea1" style="display:none"></iframe>

		<div id="tab">

			<table id="headerTable" class="table table-hover table-bordered" style="font-size: 13px;">

				<tr class="bg-primary" >
					<th  height="4px" scope="col"><center>Curso</center></th>
					<th  scope="col"><center>Nombre</center></th>
					<th  scope="col"><center>Apellido</center></th>
					<th  scope="col"><center>Dni</center></th>
					<th  scope="col"><center>Telefono</center></td>
					<th  scope="col"><center>Email</center></th>
					<th  scope="col"><center>Proc</center></th>
				</tr>

				<tbody>
					{% if object_list %}
					{% for persona in filter.qs %}

					<tr >
						<td  width="auto"><center>{{ persona.codigocurso|upper }}</center></td>
						<td width="auto"><center>{{ persona.nombre|upper }}</center></td>
						<td width="auto"><center>{{ persona.apellidos|upper }}</center></td>
						<td width="auto"><center>{{ persona.dni }}</center></td>
						<td width="auto"><center>{{ persona.telefono }}</center></td>
						<td width="auto"><center>{{ persona.email }}</center></td>
						<td width="auto"><center>{{ persona.procurador|upper }}</center></td>

					</tr>



					{% endfor %}
					{{ persona.forloop.count }}
					{% else %}
					<h3>Todavía no hay suscriptores</h3>
					{% endif %}
				</tbody>

			</table>
		</div>

    </div>

    <table class="table">
	<thead>
		<tr>
			<td>
                {% if page_obj.has_previous %}
       	         <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
		        {% endif %}
            </td>
			<td>
               		{% if page_obj.has_next %}
     	             <a href="?page={{ page_obj.next_page_number }}">Next</a>
    	            {% endif %}
            </td>
        </tr>
    </thead>
    </table>
</center>
<br>
        </div>
      </div>
    </div>

</main>

</body>


{% endblock %}