public_html/core/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
]

public_html/pruebaformularios/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import PersonaList, add_persona


prueba_patterns = ([
    path('', add_persona, name='plist'),
    path('listar/', login_required(PersonaList.as_view()), name='padd'),
    ], "inscripcion")

public_html/webplayground/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from pages.urls import pages_patterns
from pruebaformularios.urls import prueba_patterns


urlpatterns = [
    path('', include('core.urls')),
    path('pages/', include(pages_patterns)),
    path('admin/', admin.site.urls),
    path('inscripcion/', include(prueba_patterns, namespace="upersonas")),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Titulos personalizados admin
admin.site.site_header ="IAPP - Instituto de Actualización y Perfecionamiento Profesional"
admin.site.index_title = "Panel de edición"
admin.site.site_title = "IAPP"

public_html/core/models.py
from django.db import models

# Create your models here.

public_html/core/views.py
from django.views.generic.base import TemplateView
from django.shortcuts import render

   
class HomePageView(TemplateView):
    template_name = "core/home.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title':"Mi Super Web Playground"})

public_html/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %} | IAPP</title>
 {% load static %}
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="{% static 'core/css/clean-blog.min.css' %}" rel="stylesheet">


  </head>
  <body>

      <!-- Navegación -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">IAPP</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ned" aria-controls="ned" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="ned">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'home' %}" >Inicio</a>
              </li>
              <li class="nav-item {% if request.path == '/pages/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'pages:pages' %}">Cursos</a>
              </li>    

			{% if request.user.is_authenticated %}
			
              <li class="nav-item">
                <a class="nav-link" style="color:#49b3f0;" href="{% url 'upersonas:padd' %}">Ver Suscriptores..</a>
			  </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:logout' %}">Cerrar Sesion</a>
              </li>
            {% endif %}
            </ul>

          </div>
        </div>
      </nav>

          <!-- Cabecera -->

      <header class="masthead" style="background-image: url('{% block background %}{% endblock %}');background-size:cover">
      <div class="overlay" style="box-shadow: 0 0 10px 2px grey;"></div>
      <div class="container" >
        <div class="row">
          <div class="col-lg-6 col-md-10 mx-auto" >
            <div class="site-heading" >
              {% block headers %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
    </header>

      <!-- Contenido -->
      {% block content %}{% endblock %}
       <!-- Pié de página -->
    <footer>
            <p class="copyright" style="color:white">Copyright &copy; 2019 · Charlie Pioli</p>
    </footer>
      <!-- Javascript -->
      <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'core/js/main.js' %}"></script>

  </body>
</html>

public_html/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Inicio{% endblock %}
{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}
{% block headers %}
	<h3 STYLE="text-shadow: 3px 3px 2px #434242;color:#f0f0f0" >INSTITUTO DE ACTUALIZACIÓN Y PERFECCIONAMIENTO PROFESIONAL</h3>
	<h8  STYLE="text-shadow: 3px 3px 2px #434242;padding: 5px 0 0 0;" >Colegio de Procuradores de Rosario</h8>
{% endblock %}
{% block content %}
<br>
<center><STRONG><UNDERLINE><h3 style="text-shadow: 2px 1px 1px gray;color:#f0f0f0";>ACERCA DE NOSOTROS</h3></UNDERLINE></STRONG></center>
<main role="main"  style="background-color:#333333;">
			{% load user_agents %}
			{% if request|is_mobile or request|is_tablet %}

				<div class="container" style="width:93%;background-color:#ababab;box-shadow: 0 0 10px 5px grey;">
			{% else %}
					<div class="container" style="width:65%;background-color:#ababab;box-shadow: 0 0 10px 5px grey;">
			{% endif %}

			<div class="col-xs-12 col-xl-10 col-lg-10 col-md-10 mt-4 mb-3 mx-auto">
			<div class="row">
			<justify>
					<p align="justify">
						<br>
						El Instituto de Actualización y Perfeccionamiento Profesional, tiene por objetivo brindar una capacitación constante y actualizada para los profesionales afines al poder judicial.<br> Nuestras Jornadas y cursos son dictados por Docentes y Profesionales especialistas en el tema en cuestión.
						<br>A través de esta página web se informará sobre los próximos cursos y jornadas que se dictarán y a los cuales podrá inscribirse en forma online, para esto deberá ir al menu "Cursos" y allí le aparecerá el listado del curso que se dará próximo como
					    los cursos que ya se dieron anteriormente (sección finalizados), para preinscribirse haga click en "INSCRIBIRSE" y rellene el formulario de preinscripción.
						<br>Por dudas o sugerencias contactese al administrador: <a href="mailto:contacto@iapprosario.com">contacto@iapprosario.com</a>
						<blockquote>
						<p style="text-align: justify;"></p>
						</blockquote>
						<br>
						   Directores IAPP:
						<ul>
						   <li>Dr.Alejandro Riera (Abogado)</li>
						   <li>Dr.Rodrigo Sebastian Dominguez (Procurador)</li>
						</ul>
						<br>
					</p>
		   </justify>
		  </div>
		  </div>
			</div>
</main>
{% endblock %}

public_html/core/templates/core/sample.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-3">
        <img src="{% static 'core/img/placeholder.png' %}" class="img-fluid"/>
      </div>
      <div class="col-md-6 mt-3">
        <h3>Página de prueba</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit nibh vel faucibus auctor. 
          Phasellus non arcu dictum, porttitor orci sed, maximus ligula. Duis mollis pulvinar tempor. 
          Cras ex nisl, fringilla ut rhoncus a, vestibulum ac turpis.</p>
      </div>
    </div>
  </div>
</main>
{% endblock %}